name: Build Ubuntu Release

on: [push, delete, pull_request]

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Release
      run: ./setup_release.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: plum
        path: plum.tar.gz